language: python
python:
- '3.6'
- '3.5'
install:
- rvm use 2.2.8 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.2.1
- pip install tweepy textblob
- pip install pytest pytest-cov
- pip install coveralls
script:
- pytest --cov=python-twitter-sentiment-analyzer/
after_success: coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_9f16e24bb054_key -iv $encrypted_9f16e24bb054_iv
  -in python-twitter-sentiment-analyzer\\CONFIG.py.enc -out python-twitter-sentiment-analyzer\\CONFIG.py -d
