language: python
python:
  - "3.6"
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
  - pip install tweepy textblob
  - pip install pytest pytest-cov
  - pip install coveralls
# command to run tests
script:
  - pytest --cov=python-twitter-sentiment-analyzer/
after_success:
  coveralls